### PR TITLE
Resolves multi-variables bug

### LINKED ISSUE #40: Backend does not properly process multi-queries with redundant parts
**Describe the bug**
Creating a query for a set of PVs that included a repeated part fail when using the `(pv:1|pv:2):other` formatting.

**To Reproduce**
1. create either a query while the backend-only option is active or create a query and and alert rule based upon that query.
2. This query should have the use the multi-PV sytnax of `(pv:name:1|pv:name:2|etc...)` but must also include a a portion of the name that is outside the multi-PV statement. For example `prefix:(pv:name:1|pv:name:2|etc...):suffix` where both prefix and suffix are optional so long as at least one of the two exist will cause the issues.
3. If you are using the backned-only option, the plot will fail to draw. If using the frontend with an alert, the "test rule" button will return no data.

**Expected behavior**
A PV query like `(EM1K0:GMD|EM2K0:XGMD):GCC:10:PRESS_RBV` should be handled like two separate queries for `EM1K0:GMD:GCC:10:PRESS_RBV` and `EM2K0:XGMD:GCC:10:PRESS_RBV`. 

**Additional context**
 - Backend issue

### PR DESCRIPTION
**Pull request by n-wbrown**
Allows PVs of the form `prefix:(var:1|var:2|...|):intermediate:(a|b|...):suffix` to work properly with the backend and alerting. 

Closes #40

### CODE REVIEW

File: pkg/archiver-query.go [hunk 1]
```diff
@@ -279,16 +280,120 @@ func IsolateBasicQuery(unparsed string) []string {
...
+            {
+                {"a", "b"}
+                {"c", "d"}
+            }
+
+        output:
+            {
+                {"a", "c"}
+                {"a", "d"}
+                {"d", "c"}
```
Comment (sasaki77) [inline pkg/archiver-query.go:327]: This comment should be `{"b", "c"}`, right?

**Comment by klauer** [comment]
What would happen with nested (invalid, I suppose) syntax such as `prefix:(var:1|(var:2|var:3)|var:4):suffix`?

File: pkg/archiver-query.go (hunk 1 above)
Comment (n-wbrown) [reply pkg/archiver-query.go]: Good catch! I've pushed a fix.

**Comment by n-wbrown** [comment]
@klauer Currently that's not supported. I would be interested in adding that though. What are your thoughts @sasaki77 ?

**Comment by sasaki77** [comment]
@n-wbrown Should I create a new release before merging #42? If so, I'll release 1.3.1.

**Comment by n-wbrown** [comment]
That would be great. #42 needs some work before it will be ready.

**Comment by sasaki77** [comment]
@klauer, @n-wbrown,  That sounds interesting. Actually, that would be helpful if AA server supported full regular expression. In any case, it's worth to add this feature.
